import { create } from 'zustand'

export const useStore = create((set) => ({
  activeTab: 'screener',
  setActiveTab: (tab) => set({ activeTab: tab }),
  backendOnline: null,
  setBackendOnline: (s) => set({ backendOnline: s }),
  screenerMode: 'INTRADAY',
  screenerResults: null,
  screenerLoading: false,
  screenerError: null,
  setScreenerMode: (m) => set({ screenerMode: m }),
  setScreenerResults: (r) => set({ screenerResults: r }),
  setScreenerLoading: (v) => set({ screenerLoading: v }),
  setScreenerError: (e) => set({ screenerError: e }),
  analyticTicker: '',
  analyticMode: 'INTRADAY',
  analyticResult: null,
  analyticBatch: null,
  analyticBatchResults: [],
  analyticLoading: false,
  analyticError: null,
  setAnalyticTicker: (t) => set({ analyticTicker: t }),
  setAnalyticMode: (m) => set({ analyticMode: m }),
  setAnalyticResult: (r) => set({ analyticResult: r }),
  setAnalyticBatchResults: (r) => set({ analyticBatchResults: r }),
  setAnalyticLoading: (v) => set({ analyticLoading: v }),
  setAnalyticError: (e) => set({ analyticError: e }),
  screenerSelectedStock: null,
  setScreenerSelectedStock: (s) => set({ screenerSelectedStock: s }),
  sendToAnalytic: (ticker, mode, screenerStock) => set({
    analyticTicker: ticker,
    activeTab: 'analytic',
    ...(mode ? { analyticMode: mode.toLowerCase() } : {}),
    screenerSelectedStock: screenerStock || null,  // SA-4: pass full screener result
    analyticBatch: null,
    analyticBatchResults: [],
  }),
  sendBatchToAnalytic: (stocks, mode) => set({
    analyticTicker: '',
    analyticResult: null,
    activeTab: 'analytic',
    ...(mode ? { analyticMode: mode.toLowerCase() } : {}),
    screenerSelectedStock: null,
    analyticBatch: {
      source: 'manual_top_gainer_batch',
      stocks: Array.isArray(stocks) ? stocks.slice(0, 3) : [],
    },
    analyticBatchResults: [],
  }),
  monitoringInput: null,
  monitoringPositions: [],
  setMonitoringPositions: (p) => set({ monitoringPositions: p }),
  sendToMonitoring: (data) => { set({ monitoringInput: null, activeTab: 'monitoring' }); setTimeout(() => set({ monitoringInput: data }), 50) },
  setMonitoringInput: (data) => set({ monitoringInput: data }),
  scalpingTicker: '',
  setScalpingTicker: (t) => set({ scalpingTicker: t }),
}))
