import { create } from 'zustand'

export const useStore = create((set) => ({
  activeTab: 'screener',
  setActiveTab: (tab) => set({ activeTab: tab }),
  backendOnline: null,
  setBackendOnline: (s) => set({ backendOnline: s }),
  screenerMode: 'DAYTRADING',
  screenerResults: null,
  screenerLoading: false,
  screenerError: null,
  setScreenerMode: (m) => set({ screenerMode: m }),
  setScreenerResults: (r) => set({ screenerResults: r }),
  setScreenerLoading: (v) => set({ screenerLoading: v }),
  setScreenerError: (e) => set({ screenerError: e }),
  analyticTicker: '',
  analyticMode: 'DAYTRADING',
  analyticResult: null,
  analyticLoading: false,
  analyticError: null,
  setAnalyticTicker: (t) => set({ analyticTicker: t }),
  setAnalyticMode: (m) => set({ analyticMode: m }),
  setAnalyticResult: (r) => set({ analyticResult: r }),
  setAnalyticLoading: (v) => set({ analyticLoading: v }),
  setAnalyticError: (e) => set({ analyticError: e }),
  sendToAnalytic: (ticker) => set({ analyticTicker: ticker, activeTab: 'analytic' }),
  monitoringInput: null,
  monitoringPositions: [],
  setMonitoringPositions: (p) => set({ monitoringPositions: p }),
  sendToMonitoring: (data) => set({ monitoringInput: data, activeTab: 'monitoring' }),
  setMonitoringInput: (data) => set({ monitoringInput: data }),
  scalpingTicker: '',
  setScalpingTicker: (t) => set({ scalpingTicker: t }),
}))
